name: Build and Publish

on:
  push:
    # TODO: reset to main
     branches: [ dev ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker and Helm
      env:
        AWS_ACCOUNT_NO: "368433847371"
        ECR_REGISTRY_ID: fast-react-static-renderer-build-image
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-2
      run: |
        echo "running scripts/ci/publish.sh"
        ./scripts/ci/publish.sh
