name: Create Git Tag


on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to create'
        required: true
      message:
        description: 'message for the tag'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create tag
        run: |
          # git config --local user.email "Workflow: ${{ env.GITHUB_WORKFLOW }}[bot]"
          # git config --local user.name "${{ env.GITHUB_WORKFLOW }}[bot]@workflow"
          echo "
          TODO: Creating a tag through this workflow does not seem to trigger the tag created workflow
          
          Do it manually for now:
          git tag -a ${{ github.event.inputs.tag }} -m \"${{ github.event.inputs.message }}\"
          git push origin ${{ github.event.inputs.tag }}
          "